import type en from './src/i18n/en.json';

declare module '@tolgee/web' {
  type TranslationsType = typeof en;

  // this will make sure that nested keys are accessible with "."
  // if you use only flat keys, it's not necessary
  type DotNotationEntries<T> = T extends object
    ? {
        [K in keyof T]: `${K & string}${T[K] extends undefined
          ? ''
          : T[K] extends object
          ? `.${DotNotationEntries<T[K]>}`
          : ''}`;
      }[keyof T]
    : '';

  // Blub Blub fork keys. `src/i18n/en.json` is generated by `tolgee pull` from
  // upstream Tolgee project 1, so fork-only keys can never appear there and are
  // declared here instead. They resolve from `defaultValue` at runtime.
  type BlubBlubTranslationKey =
    | 'activity_binary_asset_create'
    | 'activity_binary_asset_delete'
    | 'activity_binary_asset_source_replace'
    | 'activity_binary_asset_transcript_link'
    | 'activity_binary_asset_transcript_unlink'
    | 'activity_binary_asset_translation_delete'
    | 'activity_binary_asset_translation_upsert'
    | 'activity_binary_asset_update'
    | 'binary_assets_choose_file'
    | 'binary_assets_count'
    | 'binary_assets_create'
    | 'binary_assets_create_failed'
    | 'binary_assets_delete'
    | 'binary_assets_download'
    | 'binary_assets_empty'
    | 'binary_assets_filter_audio'
    | 'binary_assets_filter_clear'
    | 'binary_assets_filter_image'
    | 'binary_assets_filter_summary'
    | 'binary_assets_filter_video'
    | 'binary_assets_help'
    | 'binary_assets_load_failed'
    | 'binary_assets_name'
    | 'binary_assets_replace_source'
    | 'binary_assets_search'
    | 'binary_assets_source'
    | 'binary_assets_title'
    | 'binary_assets_transcript'
    | 'binary_assets_transcript_add'
    | 'binary_assets_transcript_add_translation'
    | 'binary_assets_transcript_cell_placeholder'
    | 'binary_assets_transcript_cancel'
    | 'binary_assets_transcript_delete'
    | 'binary_assets_transcript_deleted'
    | 'binary_assets_transcript_edit'
    | 'binary_assets_transcript_empty'
    | 'binary_assets_transcript_help'
    | 'binary_assets_transcript_key_id'
    | 'binary_assets_transcript_link'
    | 'binary_assets_transcript_link_save'
    | 'binary_assets_transcript_linked'
    | 'binary_assets_transcript_save'
    | 'binary_assets_transcript_text_placeholder'
    | 'binary_assets_transcript_unlink'
    | 'binary_assets_translations'
    | 'binary_assets_type_filter'
    | 'project_dashboard_asset_translation_current'
    | 'project_dashboard_asset_translation_missing'
    | 'project_dashboard_asset_translation_outdated'
    | 'project_dashboard_asset_translations_count'
    | 'project_dashboard_asset_translations_heading'
    | 'project_menu_assets';

  export type TranslationKey =
    | DotNotationEntries<TranslationsType>
    | BlubBlubTranslationKey;
}
